Refactoring - added Envelope.cs and used it in ResponseExtensions.cs …
aznoran/PetHouse pull request #12
Opened 2024-08-27 16:07 UTC by aznoran

…+ Injects for better flexibility. Also extracted Dtos' from CreateVolunteerRequest.cs and moved to DTOS folder

2024-08-27 21:13 UTC, Asasen1 requested changes

2024-08-27 21:13 UTC, Asasen1 commented on PetHouse.BackEnd/src/PetHouse.API/Program.cs
> +builder.Services.AddScoped<PetHouseDbContext>(_ => new PetHouseDbContext(builder.Configuration));
_ => new PetHouseDbContext(builder.Configuration) Зачем это? Убрать

2024-08-27 21:13 UTC, Asasen1 commented on PetHouse.BackEnd/src/PetHouse.Application/Inject.cs
> +    public static IServiceCollection AddApplications(this IServiceCollection serviceCollection)
В единственном числе.

2024-08-27 21:13 UTC, Asasen1 commented on PetHouse.BackEnd/src/PetHouse.Application/Inject.cs
> +        serviceCollection.AddScoped<ICreateVolunteerHandler,CreateVolunteerHandler>();
Зачем абстракция над простым хендлером?

2024-08-28 05:05 UTC, Asasen1 approved these changes
Сразу апрувну

2024-08-28 08:45 UTC, aznoran commented on PetHouse.BackEnd/src/PetHouse.API/Program.cs
> +builder.Services.AddScoped<PetHouseDbContext>(_ => new PetHouseDbContext(builder.Configuration));
у меня в pethousedbcontext передается конфигурация чтобы подключиться через connection string - иначе работать не будет. Ну у меня не работало если передавать это через сервисы, а не через конструктор

2024-08-28 08:48 UTC, merged