Id b 8
aznoran/PetHouse pull request #20
Opened 2024-09-06 22:23 UTC by aznoran

2024-09-07 05:03 UTC, YaraOduvanchik requested changes

2024-09-07 05:03 UTC, YaraOduvanchik commented on PetHouse.BackEnd/src/PetHouse.Domain/Models/Volunteers/ValueObjects/Address.cs
> +    public string? Street { get; }
Можно добавить чуть больше полей, например: Country, House
Но это по желанию

2024-09-07 05:03 UTC, YaraOduvanchik commented on PetHouse.BackEnd/src/PetHouse.Domain/Models/Volunteers/ValueObjects/PetInfo.cs
> +public class PetInfo
Это должен быть record

2024-09-20 11:09 UTC, aznoran commented
Извиняюсь сразу за кучу коммитов, в ветке много проблем возникло и вовремя не отвязался от нее, по итогу еще рефакторинг небольшой был проделан в этой же ветке, чего я заметил слишком поздно, а потом вовсе не мог целых 2 недели заниматься кодингом.

2024-09-20 12:16 UTC, YaraOduvanchik requested changes

2024-09-20 12:57 UTC, aznoran commented on PetHouse.BackEnd/src/PetHouse.API/Controllers/Volunteers/Requests/AddPetPhotoRequest.cs
> +    IFormFileCollection Photos,
у меня же в контроллер этот реквест приходит из формы. Я не могу отдельно сделать файлдто в реквесте не получив этого реквеста, из этого реквеста я уже создаю комманду где как раз таки Dto. С фронта мне приходит IFormFileCollection и поле IsMain и это все обернуто в один реквест который теряет свой смысл после первой же строки контроллера , когда я переделываю его в команду. Я не понимаю что нужно исправить

2024-09-20 12:59 UTC, KirillSachkov commented on PetHouse.BackEnd/src/PetHouse.API/Controllers/Volunteers/Requests/AddPetPhotoRequest.cs
> +    IFormFileCollection Photos,
У тебя реквесты должны лежать в слои с API, из которых ты делаешь комманды, которые лежать в application. Сейчас у тебя в слое с Application зависимость от IFromFileCollection, что не хорошо

2024-09-20 13:00 UTC, aznoran commented on PetHouse.BackEnd/src/PetHouse.API/Controllers/Volunteers/Requests/AddPetPhotoRequest.cs
> +    IFormFileCollection Photos,
у меня далее сразу идет код

```
IFormFileCollection Photos,
    bool IsMain = false)
{
    public AddPetPhotosCommand ToCommand(Guid volunteerId, Guid petId, IEnumerable<UploadFileDto> files)
    {
        return new AddPetPhotosCommand(volunteerId, petId, files, IsMain);
    }
```
где public record UploadFileDto(Stream Content, string FileName);

2024-09-20 13:16 UTC, YaraOduvanchik approved these changes

2024-09-20 13:16 UTC, merged