Id b 19
aznoran/PetHouse pull request #35
Opened 2024-10-16 15:02 UTC by aznoran

2024-10-16 15:06 UTC, aznoran commented
добавил в сидирование создание юзера админа, хотя это надо было в Б-20, но не доделал еще реализацию создания колонки в admin_accounts таблице

2024-10-17 08:29 UTC, KirillSachkov approved these changes
Посмотри комментарий, всё остальное норм

2024-10-17 08:29 UTC, KirillSachkov commented on PetHouse.BackEnd/src/Accounts/PetHouse.Accounts.Infrastructure/Managers/RoleManager.cs
> +}
rolemanager уже есть в identity, свой писать не нужно, нужно использовать готовый.

2024-10-17 08:29 UTC, KirillSachkov commented on PetHouse.BackEnd/src/PetHouse.Web/etc/accounts.json
> +      "pet-management.volunteers.pets.update.pet-status",
мне кажется было бы логичнее писать следующим образом

pet-management.volunteers.read, pet-management.pets.read, не нужно дерево такое строить из сущностей

2024-10-17 12:06 UTC, KirillSachkov requested changes

2024-10-17 12:06 UTC, KirillSachkov commented on PetHouse.BackEnd/src/PetHouse.Web/etc/accounts.json
> +      "pet-management.volunteers.pets.create",
Я бы не писал volunteers.pets.create
Можно пносто pet-management.pets.create

2024-10-17 12:21 UTC, merged